### ISSUE TITLE
The project 2 requirements

### ISSUE THREAD

**Issue by Mexator** [Mexator/Go-vno#4]
### TODO List
- [x] Sharing files between users
- [x] Name server that indexes files and detects which one where
- [x] File servers that stores files. Client can only read/write.
- [x] Client 
- [x] file operations - reading, writing, creation, deletion, copy, moving and info queries.
- [x] directory operations - listing, creation, changing and deletion
- [x] replicate files (or file parts) between 2 or more file servers. Create replication jobs if node goes offline
- [x] Fault tolerance - accessibility of  files even if some nodes offline
- [ ] Keep storage structure
- [x] Client: 
 - initialize (mount)
 - create, read, write, delete, info, copy, move - *for both dirs and files*
- [ ] File servers and NameServers should be in closed network
- [x] servers can find each other automatically
- [x] If storage server is down, create tasks for replication of chunks stored on it
- [ ] Optional: chunking of files
- [ ] Description as a document
- [ ] Presentation
- [x] All modules should be packed as images and loaded to DockerHub
- [x] README
 - Documentation how to launch and use your system
 - Architectural diagrams
 - Description of communication protocols
 - Provable contribution of each team member

### Live demo content:
- DFS Initialization
- File and directory writing, reading and deleting
- Replication
- Storage server restoration

**Comment by i1i1** [comment]
Доделать:
- [x] Rename в fuse и в nameserver-е (protobuf)
- [x] Fault tolerance (healthcheck серверов и ререпликация)
- [x] Аутентификация для неймсервера к файлсерверу (интерцепторы go-grpc)
- [x] Nameserver ищет fileserver-а
- [x] Докеризовать
- [ ] Документы

**Comment by Mexator** [comment]
Беру 2 и 4. 1 и 3 делает @i1i1. Остальные - вместе

**Comment by Mexator** [comment]
Optional: 
- [ ] Load balancing
- [ ] Redis
- [ ] Recognize fileserver if it changes IP
